# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_L.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modify_L(object):
    def setupUi(self, modify_L):
        modify_L.setObjectName("modify_L")
        modify_L.resize(800, 600)
        self.name = QtWidgets.QLabel(modify_L)
        self.name.setGeometry(QtCore.QRect(40, 40, 150, 20))
        self.name.setObjectName("name")
        self.start = QtWidgets.QLabel(modify_L)
        self.start.setGeometry(QtCore.QRect(40, 80, 150, 20))
        self.start.setObjectName("start")
        self.end = QtWidgets.QLabel(modify_L)
        self.end.setGeometry(QtCore.QRect(40, 120, 150, 20))
        self.end.setObjectName("end")
        self.mileage = QtWidgets.QLabel(modify_L)
        self.mileage.setGeometry(QtCore.QRect(40, 160, 150, 20))
        self.mileage.setObjectName("mileage")
        self.open = QtWidgets.QLabel(modify_L)
        self.open.setGeometry(QtCore.QRect(40, 240, 150, 20))
        self.open.setObjectName("open")
        self.intro = QtWidgets.QLabel(modify_L)
        self.intro.setGeometry(QtCore.QRect(40, 280, 150, 20))
        self.intro.setObjectName("intro")
        self.color = QtWidgets.QLabel(modify_L)
        self.color.setGeometry(QtCore.QRect(40, 200, 150, 20))
        self.color.setObjectName("color")
        self.url = QtWidgets.QLabel(modify_L)
        self.url.setGeometry(QtCore.QRect(40, 320, 150, 20))
        self.url.setObjectName("url")
        self.speed = QtWidgets.QLabel(modify_L)
        self.speed.setGeometry(QtCore.QRect(40, 360, 150, 20))
        self.speed.setObjectName("speed")
        self.OK = QtWidgets.QPushButton(modify_L)
        self.OK.setGeometry(QtCore.QRect(640, 480, 150, 46))
        self.OK.setObjectName("OK")
        self.Exit = QtWidgets.QPushButton(modify_L)
        self.Exit.setGeometry(QtCore.QRect(640, 540, 150, 46))
        self.Exit.setObjectName("Exit")
        self.out = QtWidgets.QTextBrowser(modify_L)
        self.out.setGeometry(QtCore.QRect(40, 400, 500, 192))
        self.out.setObjectName("out")
        self.name_input = QtWidgets.QLineEdit(modify_L)
        self.name_input.setGeometry(QtCore.QRect(190, 40, 291, 20))
        self.name_input.setObjectName("name_input")
        self.start_input = QtWidgets.QLineEdit(modify_L)
        self.start_input.setGeometry(QtCore.QRect(190, 80, 291, 20))
        self.start_input.setObjectName("start_input")
        self.end_input = QtWidgets.QLineEdit(modify_L)
        self.end_input.setGeometry(QtCore.QRect(190, 120, 291, 20))
        self.end_input.setObjectName("end_input")
        self.mileage_input = QtWidgets.QLineEdit(modify_L)
        self.mileage_input.setGeometry(QtCore.QRect(190, 160, 291, 20))
        self.mileage_input.setObjectName("mileage_input")
        self.color_input = QtWidgets.QLineEdit(modify_L)
        self.color_input.setGeometry(QtCore.QRect(190, 200, 291, 20))
        self.color_input.setObjectName("color_input")
        self.open_input = QtWidgets.QLineEdit(modify_L)
        self.open_input.setGeometry(QtCore.QRect(190, 240, 291, 20))
        self.open_input.setObjectName("open_input")
        self.intro_input = QtWidgets.QLineEdit(modify_L)
        self.intro_input.setGeometry(QtCore.QRect(190, 280, 291, 20))
        self.intro_input.setObjectName("intro_input")
        self.url_input = QtWidgets.QLineEdit(modify_L)
        self.url_input.setGeometry(QtCore.QRect(190, 320, 291, 20))
        self.url_input.setObjectName("url_input")
        self.speed_input = QtWidgets.QLineEdit(modify_L)
        self.speed_input.setGeometry(QtCore.QRect(190, 360, 291, 20))
        self.speed_input.setObjectName("speed_input")

        self.retranslateUi(modify_L)
        QtCore.QMetaObject.connectSlotsByName(modify_L)

    def retranslateUi(self, modify_L):
        _translate = QtCore.QCoreApplication.translate
        modify_L.setWindowTitle(_translate("modify_L", "Form"))
        self.name.setText(_translate("modify_L", "chinese name:"))
        self.start.setText(_translate("modify_L", "start time:"))
        self.end.setText(_translate("modify_L", "end time:"))
        self.mileage.setText(_translate("modify_L", "mileage:"))
        self.open.setText(_translate("modify_L", "first opening:"))
        self.intro.setText(_translate("modify_L", "intro:"))
        self.color.setText(_translate("modify_L", "color:"))
        self.url.setText(_translate("modify_L", "url:"))
        self.speed.setText(_translate("modify_L", "speed:"))
        self.OK.setText(_translate("modify_L", "OK"))
        self.Exit.setText(_translate("modify_L", "Exit"))
