# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogWindow(object):
    def setupUi(self, LogWindow):
        LogWindow.setObjectName("LogWindow")
        LogWindow.resize(800, 600)
        self.UserName = QtWidgets.QLineEdit(LogWindow)
        self.UserName.setGeometry(QtCore.QRect(280, 180, 226, 40))
        self.UserName.setObjectName("UserName")
        self.Password_2 = QtWidgets.QLineEdit(LogWindow)
        self.Password_2.setGeometry(QtCore.QRect(280, 240, 226, 40))
        self.Password_2.setObjectName("Password_2")
        self.USer = QtWidgets.QLabel(LogWindow)
        self.USer.setGeometry(QtCore.QRect(200, 180, 62, 40))
        self.USer.setObjectName("USer")
        self.Password = QtWidgets.QLabel(LogWindow)
        self.Password.setGeometry(QtCore.QRect(160, 240, 108, 32))
        self.Password.setObjectName("Password")
        self.LogIn = QtWidgets.QLabel(LogWindow)
        self.LogIn.setGeometry(QtCore.QRect(360, 120, 82, 32))
        self.LogIn.setObjectName("LogIn")
        self.LogIn_2 = QtWidgets.QPushButton(LogWindow)
        self.LogIn_2.setGeometry(QtCore.QRect(260, 300, 122, 46))
        self.LogIn_2.setObjectName("LogIn_2")
        self.UserTips = QtWidgets.QLabel(LogWindow)
        self.UserTips.setGeometry(QtCore.QRect(520, 180, 200, 32))
        self.UserTips.setText("This is user tips")
        self.UserTips.setObjectName("UserTips")
        self.PasswordTips = QtWidgets.QLabel(LogWindow)
        self.PasswordTips.setGeometry(QtCore.QRect(520, 240, 200, 32))
        self.PasswordTips.setText("This is password tips")
        self.PasswordTips.setObjectName("PasswordTips")
        self.Register = QtWidgets.QPushButton(LogWindow)
        self.Register.setGeometry(QtCore.QRect(400, 300, 122, 46))
        self.Register.setObjectName("Register")

        self.retranslateUi(LogWindow)
        QtCore.QMetaObject.connectSlotsByName(LogWindow)

    def retranslateUi(self, LogWindow):
        _translate = QtCore.QCoreApplication.translate
        LogWindow.setWindowTitle(_translate("LogWindow", "Form"))
        self.USer.setText(_translate("LogWindow", "User:"))
        self.Password.setText(_translate("LogWindow", "Password:"))
        self.LogIn.setText(_translate("LogWindow", "Log in"))
        self.LogIn_2.setText(_translate("LogWindow", "Log in"))
        self.Register.setText(_translate("LogWindow", "Register"))
