# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(1000, 700)
        self.gridLayoutWidget = QtWidgets.QWidget(MainMenu)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(350, 180, 300, 400))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)

        self.gridLayout.setObjectName("gridLayout")
        self.users = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.users.setStyleSheet("font: 14pt \"Arial\";")
        self.users.setObjectName("users")
        self.gridLayout.addWidget(self.users, 1, 0, 1, 1)
        self.changeUser = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.changeUser.setStyleSheet("font: 14pt \"Arial\";")
        self.changeUser.setObjectName("changeUser")
        self.gridLayout.addWidget(self.changeUser, 2, 0, 1, 1)

        self.Admin = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Admin.setStyleSheet("font: 14pt \"Arial\";")
        self.Admin.setObjectName("Admin")
        self.gridLayout.addWidget(self.Admin, 0, 0, 1, 1)
        self.Exit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Exit.setStyleSheet("font: 14pt \"Arial\";")
        self.Exit.setObjectName("Exit")
        self.gridLayout.addWidget(self.Exit, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(MainMenu)
        self.label.setGeometry(QtCore.QRect(400, 50, 219, 71))
        self.label.setStyleSheet("font: 22pt \"Arial\";")
        self.label.setObjectName("label")

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Form"))
        self.users.setText(_translate("MainMenu", "users"))
        self.changeUser.setText(_translate("MainMenu", "changeUser"))

        self.Admin.setText(_translate("MainMenu", "Admin"))
        self.Exit.setText(_translate("MainMenu", "Exit"))
        self.label.setText(_translate("MainMenu", "    Menu"))
