# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modify_S.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modify_L(object):
    def setupUi(self, modify_L):
        modify_L.setObjectName("modify_L")
        modify_L.resize(800, 600)
        self.chinese = QtWidgets.QLabel(modify_L)
        self.chinese.setGeometry(QtCore.QRect(40, 70, 150, 12))
        self.chinese.setObjectName("chinese")
        self.english = QtWidgets.QLabel(modify_L)
        self.english.setGeometry(QtCore.QRect(40, 110, 150, 12))
        self.english.setObjectName("english")
        self.intro = QtWidgets.QLabel(modify_L)
        self.intro.setGeometry(QtCore.QRect(40, 190, 150, 12))
        self.intro.setObjectName("intro")
        self.OK = QtWidgets.QPushButton(modify_L)
        self.OK.setGeometry(QtCore.QRect(640, 480, 150, 46))
        self.OK.setObjectName("OK")
        self.Exit = QtWidgets.QPushButton(modify_L)
        self.Exit.setGeometry(QtCore.QRect(640, 540, 150, 46))
        self.Exit.setObjectName("Exit")
        self.out = QtWidgets.QTextBrowser(modify_L)
        self.out.setGeometry(QtCore.QRect(40, 400, 500, 192))
        self.out.setObjectName("out")
        self.chinese_input = QtWidgets.QLineEdit(modify_L)
        self.chinese_input.setGeometry(QtCore.QRect(190, 70, 291, 20))
        self.chinese_input.setObjectName("chinese_input")
        self.english_input = QtWidgets.QLineEdit(modify_L)
        self.english_input.setGeometry(QtCore.QRect(190, 110, 291, 20))
        self.english_input.setObjectName("english_input")
        self.intro_input = QtWidgets.QLineEdit(modify_L)
        self.intro_input.setGeometry(QtCore.QRect(190, 190, 291, 20))
        self.intro_input.setObjectName("intro_input")
        self.district = QtWidgets.QLabel(modify_L)
        self.district.setGeometry(QtCore.QRect(40, 150, 150, 12))
        self.district.setObjectName("district")
        self.district_input = QtWidgets.QLineEdit(modify_L)
        self.district_input.setGeometry(QtCore.QRect(190, 150, 291, 20))
        self.district_input.setObjectName("district_input")
        self.id_input = QtWidgets.QLineEdit(modify_L)
        self.id_input.setGeometry(QtCore.QRect(190, 30, 291, 20))
        self.id_input.setObjectName("id_input")
        self.id = QtWidgets.QLabel(modify_L)
        self.id.setGeometry(QtCore.QRect(40, 30, 150, 12))
        self.id.setObjectName("id")

        self.status_input = QtWidgets.QLineEdit(modify_L)
        self.status_input.setGeometry(QtCore.QRect(190, 230, 291, 20))
        self.status_input.setObjectName("status_input")

        self.status = QtWidgets.QLabel(modify_L)
        self.status.setGeometry(QtCore.QRect(40, 230, 78, 12))
        self.status.setObjectName("status")

        self.retranslateUi(modify_L)
        QtCore.QMetaObject.connectSlotsByName(modify_L)

    def retranslateUi(self, modify_L):
        _translate = QtCore.QCoreApplication.translate
        modify_L.setWindowTitle(_translate("modify_L", "Form"))
        self.chinese.setText(_translate("modify_L", "chinese name:"))
        self.english.setText(_translate("modify_L", "english name:"))
        self.intro.setText(_translate("modify_L", "intro:"))
        self.OK.setText(_translate("modify_L", "OK"))
        self.Exit.setText(_translate("modify_L", "Exit"))
        self.district.setText(_translate("modify_L", "district:"))
        self.id.setText(_translate("modify_L", "id:"))
        self.status.setText(_translate("modify_L","status:"))
