# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passenger_add.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modify_L(object):
    def setupUi(self, modify_L):
        modify_L.setObjectName("modify_L")
        modify_L.resize(800, 601)
        self.OK = QtWidgets.QPushButton(modify_L)
        self.OK.setGeometry(QtCore.QRect(640, 480, 150, 46))
        self.OK.setObjectName("OK")
        self.Exit = QtWidgets.QPushButton(modify_L)
        self.Exit.setGeometry(QtCore.QRect(640, 540, 150, 46))
        self.Exit.setObjectName("Exit")
        self.textBrowser = QtWidgets.QTextBrowser(modify_L)
        self.textBrowser.setGeometry(QtCore.QRect(40, 400, 500, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.name_input = QtWidgets.QLineEdit(modify_L)
        self.name_input.setGeometry(QtCore.QRect(180, 30, 291, 20))
        self.name_input.setObjectName("name_input")
        self.name = QtWidgets.QLabel(modify_L)
        self.name.setGeometry(QtCore.QRect(30, 30, 150, 20))
        self.name.setObjectName("name")
        self.gender = QtWidgets.QLabel(modify_L)
        self.gender.setGeometry(QtCore.QRect(30, 60, 150, 20))
        self.gender.setObjectName("gender")
        self.gender_input = QtWidgets.QLineEdit(modify_L)
        self.gender_input.setGeometry(QtCore.QRect(180, 60, 291, 20))
        self.gender_input.setObjectName("gender_input")
        self.id = QtWidgets.QLabel(modify_L)
        self.id.setGeometry(QtCore.QRect(30, 90, 150, 20))
        self.id.setObjectName("id")
        self.id_input = QtWidgets.QLineEdit(modify_L)
        self.id_input.setGeometry(QtCore.QRect(180, 90, 291, 20))
        self.id_input.setObjectName("id_input")
        self.phone = QtWidgets.QLabel(modify_L)
        self.phone.setGeometry(QtCore.QRect(30, 120, 150, 20))
        self.phone.setObjectName("phone")
        self.phone_input = QtWidgets.QLineEdit(modify_L)
        self.phone_input.setGeometry(QtCore.QRect(180, 120, 291, 20))
        self.phone_input.setObjectName("phone_input")
        self.district = QtWidgets.QLabel(modify_L)
        self.district.setGeometry(QtCore.QRect(30, 150, 150, 20))
        self.district.setObjectName("district")
        self.district_input = QtWidgets.QLineEdit(modify_L)
        self.district_input.setGeometry(QtCore.QRect(180, 150, 291, 20))
        self.district_input.setObjectName("district_input")

        self.retranslateUi(modify_L)
        QtCore.QMetaObject.connectSlotsByName(modify_L)

    def retranslateUi(self, modify_L):
        _translate = QtCore.QCoreApplication.translate
        modify_L.setWindowTitle(_translate("modify_L", "Form"))
        self.OK.setText(_translate("modify_L", "OK"))
        self.Exit.setText(_translate("modify_L", "Exit"))
        self.name.setText(_translate("modify_L", "name:"))
        self.gender.setText(_translate("modify_L", "gender:"))
        self.id.setText(_translate("modify_L", "id:"))
        self.phone.setText(_translate("modify_L", "phone:"))
        self.district.setText(_translate("modify_L", "district:"))
