# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 100, 600, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.shortest = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.shortest.setObjectName("shortest")
        self.gridLayout.addWidget(self.shortest, 0, 0, 1, 1)
        self.after_station = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.after_station.setObjectName("after_station")
        self.gridLayout.addWidget(self.after_station, 1, 1, 1, 1)
        self.passenger = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.passenger.setObjectName("passenger")
        self.gridLayout.addWidget(self.passenger, 2, 1, 1, 1)
        self.prices = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.prices.setObjectName("prices")
        self.gridLayout.addWidget(self.prices, 0, 1, 1, 1)
        self.lines = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lines.setObjectName("lines")
        self.gridLayout.addWidget(self.lines, 1, 0, 1, 1)
        self.card = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.card.setObjectName("card")
        self.gridLayout.addWidget(self.card, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.change_pass = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.change_pass.setObjectName("pushButton")
        self.gridLayout.addWidget(self.change_pass, 1, 2, 1, 1)
        self.delete_self = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.delete_self.setObjectName("pushButton")
        self.gridLayout.addWidget(self.delete_self, 2, 2, 1, 1)
        self.Back = QtWidgets.QCommandLinkButton(Form)
        self.Back.setGeometry(QtCore.QRect(610, 500, 91, 41))
        self.Back.setObjectName("commandLinkButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.shortest.setText(_translate("Form", "The shortest way"))
        self.after_station.setText(_translate("Form", "Stations after"))
        self.passenger.setText(_translate("Form", "Passenger ride"))
        self.prices.setText(_translate("Form", "Price from a to b"))
        self.lines.setText(_translate("Form", "Search lines"))
        self.card.setText(_translate("Form", "Card ride"))
        self.pushButton.setText(_translate("Form", "Search stations"))
        self.change_pass.setText(_translate("Form", "change pass"))
        self.delete_self.setText(_translate("Form", "delete self"))
        self.Back.setText(_translate("Form", "Back"))
